[General]
__userfile__=true
panels=panel1

[panel1]
plugins=mainmenu,showdesktop,quicklaunch,taskbar,desktopswitch,spacer,statusnotifier,spacer,clock
position=Bottom
align=Left
width=100%
height=36
iconSize=22
lineCount=1
background=#121820
fontColor=#e2e8f0
autoHide=false

[mainmenu]
type=mainmenu

[showdesktop]
type=showdesktop

[quicklaunch]
type=quicklaunch
apps\1\desktop=/usr/share/applications/xfce4-terminal.desktop
apps\2\desktop=/usr/share/applications/firefox.desktop

[taskbar]
type=taskbar
settings\onlyCurrentDesktop=false
settings\showOnlyMinimized=false
settings\buttonWidth=150

[desktopswitch]
type=desktopswitch
settings\rows=1

[spacer]
type=spacer

[statusnotifier]
type=statusnotifier

[clock]
type=clock
settings\format=hh:mm AP
settings\showDate=true
settings\datePosition=Below
