[Desktop]
Wallpaper=/usr/share/backgrounds/novaos/novaos-default.png
WallpaperMode=stretch
ShowFiles=true
GridAlign=true
ShowTrashCan=false
ShowMounts=true
IconSize=48

[Volume]
MountOnInsert=true
MountOnStart=true
