[General]
window_manager=openbox
leave_confirmation=true
theme=Arc-Dark
icon_theme=Papirus-Dark

[Environment]
GTK_CSD=0
GTK_OVERLAY_SCROLLING=0

[Mouse]
cursor_size=24
cursor_theme=Adwaita

[Keyboard]
delay=500
interval=30
beep=false

[Font]
antialias=true
hinting=true
dpi=96
