[greeter]
background=/usr/share/backgrounds/novaos/novaos-default.png
theme-name=Adwaita-dark
icon-theme-name=Adwaita
font-name=Sans 10
xft-antialias=true
xft-dpi=96
xft-hintstyle=hintslight
xft-rgba=rgb
indicators=~host;~spacer;~clock;~spacer;~session;~power
user-background=false
hide-user-image=true
